Pelagicore/pelux.io

get-involved.md
Tried to be consistent with PELUX as all uppercase everywhere
Some native English fixes
=> Minor changes and typo fixes

get-involved.md
Not everybody has a IRC client set up already, this link helps them
to join the IRC chanel from their browser without the need to install
anything.
=> Add IRC webclient link to get involved

README.md
In the README the how to build instructions tell the user to use
gem install, but they should use bundle install instead, so they
would get the right versions of the gems according to the Gemfile.
=> readme: Replace gem install with bundle install

Gemfile, Gemfile.lock, Jenkinsfile, _config.yml
To be independent of gh-pages we need to build the website ourselves,
and to do so the easiest way it doing it with Jenkins. This
Jenkinsfile clones the repo installs the necessary ruby gems,
builds the website and archives the _site directory.
A different job will then move the static files to a webserver.
=> Add a Jenkinsfile

README.md
When building the gems, on a debian based system per default there
are no headers installed which makes the bundle install break.
=> Add ruby-dev as debian host  dependency

Jenkinsfile
Dont't run tests untill we have moved the IRC logs because the
build server can't reach it for some reason and fails for now,
which it shouldn't.
=> Remove Test stage for now

_config.yml
We don't own a registered trademark here, let's not claim it
=> Remove the (R) symbol from the webpage's title

roadmap.md
It was decided that the focus will not be on SDL for the upcoming
releases.
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>
=> roadmap.md: Remove SDL from the roadmap

Jenkinsfile
It turns out this made the Jenkinsfile too specific and also restricted
where this job could run, since that node needed access to /var/www.
This reverts commit 2788c6787b6007e43604ae06bc62a783dfea217d.
=> Revert "Jenkinsfile: deploy automatically if master branch"

download.md
The Software Factory link has been changed because the site is now
being versioned.
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.comm>
=> download: Fix broken link

demo.md
As [discussed on IRC](http://pelux.io/irclogs/channels/%23PELUX/2018-01-22/), the current video on http://pelux.io/demo/ is broken. thenor proposed to replace the previous link with a newer one from CES: https://www.youtube.com/watch?v=x8SOfRLP8_M
=> demo.md: Update to a newer and working video of ARP+Pelux at CES

Gemfile, Gemfile.lock
Due to a vulnerability in libxml2 the nokogiri version needs to be updated.
=> Gemfile: update nokogiri version

Dockerfile, Jenkinsfile, _config.yml
This way, we don't need to worry about dependencies other than Docker on
our build servers, and the Dockerfile shows clearly what the
dependencies are in case someone wonders.
=> Build the site in a Docker container instead

README.md, download.md
For some reason, the lvl1 headings are smaller than the lvl2 headings
when used in the markdown. We just change to make everything one level
smaller.
=> download.md: smaller headings avoid css weirdness

_posts/2018-04-04-QtWebEngine-on-Rpi3.md
This blogpost details how we ended up reporting a bug that touches QtWayland, QtWebEngine, QtQuick and QtPorts.
Based on https://github.com/Pelagicore/pelux.io/pull/69 (but I couldn't push to gordan's branch so I had to create a new PR, sorry for that :) )
+ slightly off-topic: I also found out why I had to ask how to manually add reviewers to my PR during last meeting: I can't add reviewers, probably due to insufficient rights on this repository?
=> posts: QtWebEngine on Raspberry Pi 3 blogpost

_config.yml
* Fixed spelling
* Changed copyright to Luxoft Sweden AB
=> config: Fix spelling and copyright

Gemfile.lock, Jenkinsfile, downloads-v1.0.md
Change IP for Jenkins, so new Jenkins can build.
Change the title of v1.0 download page, so we don't have duplicates.
Update gem versions.
=> Adaptation for 'new Jenkins' and bug fixes

Jenkinsfile
Use internal IP for Vladimir build server.
Update archive function to archiveArtifacts.
=> Jenkinsfile: fix ip and deprecated function

Jenkinsfile
The migration to use the new server for pelux.io is ongoing but not
completed. Until it is migrated completely and the domain points
to the new server we will use a temporary domain.
=> Jenkinsfile: remove hardcoded IP, but use temp domain

_download/v1.0.md, download.md
The links on the website point to the swf tag builds and will be
changed to point to the release branch instead, since the tags are
linked to a specific commit and any bug fixes or other necessary updates
on the release branches won't take effect or be visible.
=> Use branch names instead of tags for swf links

roadmap.md
Version 3.0 has been released so not part of the roadmap.
=> roadmap.md: Removed PELUX 3.0

Jenkinsfile, _posts/2018-01-12-PELUX-1.0.md, _posts/2018-07-02-PELUX-2.0.md, _posts/2018-11-19-PELUX-3.0.md
htmlproofer found a couple of broken links from blogposts due to the renaming of downloads to releases, and these links have been fixed.
The webserver needs to be fixed regarding the /irclogs link and until this has been fixed, the check for external links have been disabled. Another problem with that fix is that all external link checks fails when executed by Jenkins using docker.
=> htmlproofer fixes

_config.yml, _release/v1.0.md, _release/v2.0.md, releases.md
Renamed collection used to store info about releases for consitency
as the main page has been renamed from downloads to releases.
=> releases: rename download collection to release

README.md
Removed Richard as a maintainer since the software-factory is maintained
mainly by the PELUX project nowadays.
Also added Luxoft Sweden AB copyright.
=> README: change copyright and remove maintainer
