_config.yml
_includes/footer.html

If people would like to contribute to the website it is a nice thing
to have a link back to the source code.

Add link to github repo of the website

---

demo.md

Fixed a typo

---

documentation.md
get-involved.md
index.md
roadmap.md

Added more text to most sections of the web page. Also some minor rewording and fixing of typos.

More text for the web site

---

_posts/2017-06-19-How-to-create-a-shared-sstate-dir.md

Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

posts: Yocto shared sstate-cache directory

---

index.md

Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

index.md: Change headline

---

_posts/2017-06-07-Why-GENIVI-DLT-as-logging-aggregator.md

Minor syntax and spell checking. Typo fixing.

---

components.md

Add a link to QtIvi and change the NeptuneUI link to point to the user oriented site.

Expand QtAuto section

---

roadmap.md

See original thread: https://github.com/Pelagicore/pelux.io/pull/30

Adding a first version to the roadmap - squashed changes

---

Jenkinsfile

Various minor fixes (whitespace + spelling)

Automatically deploy if on master branch

---

Jenkinsfile

Jenkinsfile: mv instead of cp for ngingx serve

---

documentation.md

documentation: use pelux.io instead of github

---

_posts/2017-10-27-QtAuto-on-Raspberry-Pi.md

add blogpost about QtAs on the rPi 3

---

roadmap.md

Added some nice links as well.

roadmap: update timing/contents of PELUX 1.0

---

README.md
_includes/head.html
_layouts/home.html
components.md
demo.md
documentation.md
download.md
get-involved.md
index.md

fix long lines and trailing whitespace

---

download.md

download: add link for source build

---

roadmap.md

Move release 1.0 to December 2017

---

roadmap.md

roadmap: less specific about 2018

---

roadmap.md

postpone first release until Jan 2018

---

Jenkinsfile
components.md
documentation.md
download.md
get-involved.md

Run the site tests in the Jenkinsfile

---

_posts/2018-01-12-PELUX-1.0.md

Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

PELUX 1.0 Release blog post edit

---

_config.yml
_includes/footer.html

Include copyright and license info in site footer

---

components.md

Once https://github.com/Pelagicore/pelux-manifests/pull/119 will be merged, we will have a new layer. It'll be fair to update the website accordingly.

components.md: Add meta-swupdate to the list of layers

---

get-involved.md

get-involved: add web-irc iframe

---

_posts/2018-03-29-Yocto-Training.md

fix relative linking in latest blog post

---

roadmap.md

roadmap: improve spelling

---

_posts/2017-10-27-QtAuto-on-Raspberry-Pi.md
_posts/2018-04-04-QtWebEngine-on-Rpi3.md

Signed-off-by: Fisnik Hajredini <fhajredini@luxoft.com>

Fix broken links

---

Gemfile.lock

Gemfile: update nokogiri

---

components.md

components.md: Fix spelling

---

get-involved.md

get-involved: Fix spelling

---

index.md

index.md: Improve formatting and spelling

---

_posts/2018-07-02-PELUX-2.0.md

blog: PELUX 2.0 release announcement

---

_posts/2018-07-02-PELUX-2.0.md

blogpost: Updating the time for the release

---

_posts/2018-07-02-PELUX-2.0.md

blogpost: Change time for release

---

download.md

downloads: Add links to old releases

---

download.md

downloads: fix formatting for old releases

---

_posts/2018-07-02-PELUX-2.0.md

blogpost: Update time

---

roadmap.md

roadmap: add info on PELUX 3.0

---

Gemfile.lock

Potential security vulnerability in ffi 1.9.18.

Gemfile.lock: update ffi version

---

roadmap.md

roadmap: fix 3.0 planned release date

---

Dockerfile

Dockerfile: upgrade image to Ubuntu 18.04

---

Jenkinsfile
_config.yml
_download/v1.0.md
download.md

downloads: use jekyll collections for releases

---

_posts/2018-11-19-PELUX-3.0.md

blog: PELUX 3.0 release announcement

---

_download/v2.0.md
download.md

downloads: add PELUX 3.0

---

download.md

Signed-off-by: Fisnik Hajredini <fhajredini@luxoft.com>

Downloads 3.0: Fix broken link on qt-auto and add link to sources

---

download.md

Also update to use GB instead of GB.

downloads: Add rpi image links and file sizes

---

_config.yml

config: change email

---

_release/v3.0.md

releases: 3.1

---

_posts/2019-03-29-PELUX-3.1.md

blog: PELUX 3.1 release announcement

---

resources.md

Signed-off-by: Fisnik Hajredini <fhajredini@luxoft.com>

resources: Add architecture section and link it

---

releases.md

releases: fix links to PELUX 3.1 artifacts

---

get-involved.md

Signed-off-by: Fisnik Hajredini <fhajredini@luxoft.com>

get-involved: Remove IRC and add the mailing list

---

_release/v3.1.md
releases.md

releases: add PELUX 4.0

---

_posts/2019-07-29-PELUX-4.0.md

blog: PELUX 4.0 release announcement

---

_release/v3.1.md
releases.md

releases: fix titles

---

releases.md

releases: fix a few links

---

Jenkinsfile

Jenkins: fix website URL

---

Gemfile
Gemfile.lock

Gemfile: update nokogiri to fix security issue
